# -----------------------------------------------
# !!! THIS FILE WAS GENERATED BY TYPE-GRAPHQL !!!
# !!!   DO NOT MODIFY THIS FILE BY YOURSELF   !!!
# -----------------------------------------------

type Query {
  setToken(token: String!): String!
  singleUser(username: String!): User!
  users: [User!]!
}

type User {
  active: Boolean!
  address_public: String!
  admin: Boolean!
  biography: String!
  birthday: String!
  blog_post_count: Float!
  blog_topic_count: Float!
  course_count: Float!
  display_name: String!
  document: String!
  email: String!
  email_public: String!
  first_name: String!
  full_name: String!
  gender: String!
  id: ID!
  last_name: String!
  lesson_count: Float!
  media_space_content_count: Float!
  phone: String!
  phone_public: String!
  photo: String!
  site_public: String!
  user_title: String!
  username: String!
}
